version: '3.5'
services:
  postgres:
    image: postgres:13.2
    ports:
      - "10593:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - './postgres-data:/var/lib/postgresql/data:rw'
